version: '3.8'
services:
  chatgambit:
    container_name: chatgambit
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - nestjs_network

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - nestjs_network

volumes:
  postgres:
    name: nest-db

networks:
  nestjs_network:
    driver: bridge
